services:
  postgres:
    image: postgres:13.8-alpine
    volumes:
      - .dockerdev/.psqlrc:/root/.psqlrc:ro
      - pg-data:/var/lib/postgresql/data
      - history:/user/local/hist
    environment:
      PSQL_HISTFILE: /user/local/hist/.psql_history
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --no-locale"
      POSTGRES_HOST_AUTH_METHOD: trust
      LANG: ja_JP.UTF-8
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

volumes:
  history:
  pg-data: